sudo: required
dist: trusty
matrix:
  include:
  - language: python
    group: edge
    python:
    - '2.7'
    # git submodules workaround
    git:
      submodules: false
      depth: false

    # env:
    # - PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1'
    services:
    - redis-server
    addons:
      postgresql: "9.5"
    before_install:
    - sudo mount -o remount,size=50% /var/ramfs # https://github.com/travis-ci/travis-ci/issues/9036
    - sudo rm -f /etc/boto.cfg # https://github.com/travis-ci/travis-ci/issues/7940
    - sudo apt-get update -y && sudo apt-get install -y libxml2-dev libxmlsec1-dev # python-saml deps
    - git submodule update --init --recursive
    - redis-server --version
    - redis-server contrib/redis/sentinel.conf --sentinel
    - cd pybossa && ln -s themes/default/translations && cd ..
    - cp settings_test.py.tmpl settings_test.py

    install:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install otpauth

    before_script:
    - redis-cli info
    - redis-cli set foo 1
    - redis-cli get foo
    - psql -c "create user rtester with createdb login password 'rtester'" -U postgres
    - psql -c "create database pybossa_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
    script:
        - alembic -c alembictest.ini stamp head
        - alembic -c alembictest.ini upgrade head
        - ./run_tests
    # notifications:
    #  slack:
    #    secure: lgJj/SealCb3hZsMvclA9VQGwx9TJrtK6ccOZiiHZpJa5in0UkRwE6ymrZ5wqwUagAVwOLYVKHdmrtPMPsaOqavnzq9ItJFqSRo8T5ZgKK+m+X9l88ROn7+QfJyPUkpblhSXMm6+s7duBjdM/no80lA4GEoNWD5G5uQwjJWQSWk=
    #  email: false
    after_success:
    - pip install coveralls
    - coveralls
