language: python
python:
  - "2.7"
env: 
  - PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1'
services:
  - redis-server
before_install:
  - sudo apt-get update && sudo apt-get install swig
  - redis-server --version
  - redis-server contrib/redis/sentinel.conf --sentinel
  - pip install coveralls --use-mirrors
before_script:
  - psql -c "create user rtester with createdb login password 'rtester'" -U postgres
  - psql -c "create database pybossa_test owner rtester encoding 'utf-8' lc_collate 'en_US.utf8' lc_ctype 'en_US.utf8' template template0;" -U postgres
script: tox 
notifications:
  email: false
  irc: "irc.freenode.net#okfn-dev"
after_success:
  - coveralls
notifications:
  hipchat: 11e2176ebb4b7372ee0d1fbc8abf4d@Github
