language: python
python:
  - "2.6"
  - "2.7"
env: 
  - PYBOSSA_SETTINGS='../settings_test.py' CACHE_DISABLED='1'
before_install:
  - sudo apt-get update && sudo apt-get install swig
install:
  - python setup.py install
before_script:
  - psql -c 'create database pybossa;' -U postgres
script: nosetests
notifications:
  email: false
  irc: "irc.freenode.net#okfn-dev"
